import { ProjectConfig } from "./project.types";

export const projects: ProjectConfig[] = [
  {
    id: "portfolio",
    image: {
      mobile: "/images/projects/portfolio--mobile.webp",
      mobile2x: "/images/projects/portfolio--mobile@2x.webp",
      tablet: "/images/projects/portfolio--tablet.webp",
      tablet2x: "/images/projects/portfolio--tablet@2x.webp",
      desktop: "/images/projects/portfolio.webp",
      desktop2x: "/images/projects/portfolio@2x.webp",
    },
    modalImage: "/images/projects/portfolio-modal.webp",
    titleKey: "projects.portfolio.title",
    modalTitleKey: "projects.portfolio.modalTitle",
    altKey: "projects.portfolio.alt",
    overviewKey: "projects.portfolio.overview",
    whatIBuiltKey: "projects.portfolio.whatIBuilt",
    challengesKey: "projects.portfolio.challenges",
    stackKey: "projects.portfolio.stack",
    links: [
      {
        label: "Vercel",
        url: "https://interactive-portfolio-ak.vercel.app",
        type: "vercel",
      },
      {
        label: "GitHub",
        url: "https://github.com/Alyona-K/interactive_portfolio",
        type: "github",
      },
    ],
  },
  {
    id: "fintrack",
    image: {
      mobile: "/images/projects/fintrack--mobile.webp",
      mobile2x: "/images/projects/fintrack--mobile@2x.webp",
      tablet: "/images/projects/fintrack--tablet.webp",
      tablet2x: "/images/projects/fintrack--tablet@2x.webp",
      desktop: "/images/projects/fintrack.webp",
      desktop2x: "/images/projects/fintrack@2x.webp",
    },
    modalImage: "/images/projects/fintrack-modal.webp",
    titleKey: "projects.fintrack.title",
    modalTitleKey: "projects.fintrack.modalTitle",
    altKey: "projects.fintrack.alt",
    overviewKey: "projects.fintrack.overview",
    whatIBuiltKey: "projects.fintrack.whatIBuilt",
    challengesKey: "projects.fintrack.challenges",
    stackKey: "projects.fintrack.stack",
    links: [
      {
        label: "Demo",
        url: "https://fintrack-demo-v.vercel.app/",
        type: "demo",
      },
      {
        label: "GitHub (Demo)",
        url: "https://github.com/Alyona-K/fintrack-demo-v",
        type: "github",
      },
      {
        label: "Full-stack",
        url: "https://financialtracker-ak.vercel.app/",
        type: "fullstack",
      },
      {
        label: "GitHub (Full-stack)",
        url: "https://github.com/Alyona-K/financial_tracker",
        type: "github",
      },
      {
        label: "Screen Recording",
        url: "https://drive.google.com/drive/folders/1_jMBqULeBlkON4jJ3fiYP8wT0_fMkQsb",
        type: "video",
      },
    ],
  },
  {
    id: "briaton",
    image: {
      mobile: "/images/projects/briaton--mobile.webp",
      mobile2x: "/images/projects/briaton--mobile@2x.webp",
      tablet: "/images/projects/briaton--tablet.webp",
      tablet2x: "/images/projects/briaton--tablet@2x.webp",
      desktop: "/images/projects/briaton.webp",
      desktop2x: "/images/projects/briaton@2x.webp",
    },
    modalImage: "/images/projects/briaton-modal.webp",
    titleKey: "projects.briaton.title",
    modalTitleKey: "projects.briaton.modalTitle",
    altKey: "projects.briaton.alt",
    overviewKey: "projects.briaton.overview",
    whatIBuiltKey: "projects.briaton.whatIBuilt",
    challengesKey: "projects.briaton.challenges",
    stackKey: "projects.briaton.stack",
    links: [
      {
        label: "Vercel",
        url: "https://alyona-k.github.io/briaton-catalog/",
        type: "vercel",
      },
      {
        label: "GitHub",
        url: "https://github.com/Alyona-K/briaton-catalog",
        type: "github",
      },
    ],
  },
  {
    id: "pawtastic",
    image: {
      mobile: "/images/projects/pawtastic--mobile.webp",
      mobile2x: "/images/projects/pawtastic--mobile@2x.webp",
      tablet: "/images/projects/pawtastic--tablet.webp",
      tablet2x: "/images/projects/pawtastic--tablet@2x.webp",
      desktop: "/images/projects/pawtastic.webp",
      desktop2x: "/images/projects/pawtastick@2x.webp",
    },
    modalImage: "/images/projects/pawtastic-modal.webp",
    titleKey: "projects.pawtastic.title",
    modalTitleKey: "projects.pawtastic.modalTitle",
    altKey: "projects.pawtastic.alt",
    overviewKey: "projects.pawtastic.overview",
    whatIBuiltKey: "projects.pawtastic.whatIBuilt",
    challengesKey: "projects.pawtastic.challenges",
    stackKey: "projects.pawtastic.stack",
    links: [
      {
        label: "Vercel",
        url: "https://alyona-k.github.io/pawtastic/",
        type: "vercel",
      },
      {
        label: "GitHub",
        url: "https://github.com/Alyona-K/pawtastic",
        type: "github",
      },
    ],
  },
];
